### ISSUE TITLE
[Bug]: [Sandbox] ERROR: for genie  "host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by mbbipul** [statuzproj/statuz#17]
### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:49Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Provider (Eg - Minikube, EKS, GCP)

<details>
   minikube
</details>

### What happened?

When i am running docker-compose up , 
Service genie not starting and it's throwing an Error.

Details
```
ERROR: for genie  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "/opt/homebrew/bin/docker-compose", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/opt/homebrew/lib/python3.11/site-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/opt/homebrew/lib/python3.11/site-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
                ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/opt/homebrew/lib/python3.11/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/opt/homebrew/lib/python3.11/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/service.py", line 939, in _get_container_create_options
    container_options['host_config'] = self._get_container_host_config(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/compose/service.py", line 1014, in _get_container_host_config
    return self.client.create_host_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/docker/api/container.py", line 608, in create_host_config
    return HostConfig(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### What did you expect to happen?

Should up all services in sandbox.

### How can we reproduce it (as minimally and precisely as possible)?

Install all dependencies and run docker-compose up for sandbox.

**Comment by timam** [comment]
@mbbipul https://github.com/statuzproj/statuz/pull/19 removes dependency on host network. 

Please follow updated [readme](https://github.com/statuzproj/statuz/blob/main/sandbox/README.md) and see if the issue persists.
